### PR TITLE
add documentation about using DOM/SSR in Deno

### PR DESCRIPTION
**Pull request by kitsonk**
Build out a section to provide information on using the DOM and SRR in Deno

### CODE REVIEW

**Comment by b-fuze** [comment]
Very cool additions. I'd like to add that:
> Currently deno-dom does not work under Deno Deploy
Deno DOM does work under Deno Deploy, it's only `querySelector[All]` that doesn't work (I'm working on an alternative for that), everything else works, including `{document,Element}.getElement{sByTagName,sClassName,Id}()`.

I think that you should include the native library under the faster startup category, if suitable for user's needs. Unlike WASM, it doesn't have the startup penalty.

**Comment by b-fuze** [comment]
I just pushed a fix for `querySelector/All` that allows it to work on Deno Deploy, so Deno DOM should work fully on Deno Deploy now.

**Comment by kitsonk** [comment]
> I just pushed a fix for `querySelector/All` that allows it to work on Deno Deploy, so Deno DOM should work fully on Deno Deploy now.

Cool.  I will update things!

**Review by bartlomieju — APPROVED** [review]
LGTM, this is great, thank you @kitsonk

**Pull request merged**
