### PR TITLE
add doc for DENO_NO_PROMPT

### PR DESCRIPTION
**Pull request by nayeemrmn**
https://github.com/denoland/deno/pull/14209

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
LGTM, please sign the CLA

**Review by bartlomieju — APPROVED** [review]
LGTM

**Review by kt3k — APPROVED** [review]
Thanks!

**Comment by bartlomieju** [comment]
> Thanks!

We shouldn't have landed this PR yet, the PR in `deno` repository hasn't been merged yet.

**Comment by kt3k** [comment]
Oh, sorry. Will revert

**Pull request merged**
