### PR TITLE
Move actions to actions/checkout@v3

### PR DESCRIPTION
**Pull request by UltiRequiem**
https://github.com/actions/checkout#checkout-v3

Similar to https://github.com/denoland/deno/pull/14089

### CODE REVIEW

**Comment by kt3k** [comment]
duplicate of #261

**Comment by UltiRequiem** [comment]
> duplicate of #261

This wasn't a duplicate, #261 updates the Docs while this one really updated the action that runs on the repo.

**Comment by kt3k** [comment]
@UltiRequiem Sorry I didn't see the filename..

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
