### PR TITLE
fixed incomplete neovim lsp setup solution

### LINKED ISSUE #532: tsserver and deno language server conflict in neovim
https://github.com/denoland/manual/blob/6be3bb86558dd9c39d4273165889d9ee309d5760/getting_started/setup_your_environment.md?plain=1#L62
This is the section for setting up deno dev environment in neovim, however I needed to also set `single_file_support = false` for tsserver to stop it from running in **single file mode**. So I thought maybe I could make a PR and add this to this section?

### PR DESCRIPTION
**Pull request by daalfox**
Closes #532 
before this, `tsserver` would run in single file mode and conflict with denols anyways

### CODE REVIEW

**Comment by kt3k** [comment]
Does anyone in @denoland/engineering use neovim?

**Comment by bartlomieju** [comment]
> Does anyone in @denoland/engineering use neovim?

CC @littledivy

**Review by magurotuna — APPROVED** [review]
I'm a neovim user and this setting makes sense 👍  LGTM

**Comment by kt3k** [comment]
@magurotuna @littledivy Thanks for checking!

**Comment by daalfox** [comment]
sorry for formatting issues, didn't know it checks markdown files too :)

**Pull request merged**
